package Frames;


import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class HomeAd extends javax.swing.JFrame {

    /**
     * Creates new form HomeAd
     */
    public HomeAd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        exit = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        A_med = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spe = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        H_ward = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Bed_M = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Dep = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Ass = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(45, 118, 232));

        exit.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(45, 118, 232));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_search_30px.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/White_png_1_250x250.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(234, 234, 234))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel8)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel22)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        A_med.setPreferredSize(new java.awt.Dimension(170, 153));
        A_med.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A_medMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A_medMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                A_medMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                A_medMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 118, 232));
        jLabel7.setText("Doctors List");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_treatment_70px_2_1.png"))); // NOI18N

        javax.swing.GroupLayout A_medLayout = new javax.swing.GroupLayout(A_med);
        A_med.setLayout(A_medLayout);
        A_medLayout.setHorizontalGroup(
            A_medLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_medLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(A_medLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_medLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123))
                    .addGroup(A_medLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        A_medLayout.setVerticalGroup(
            A_medLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_medLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        spe.setPreferredSize(new java.awt.Dimension(180, 159));
        spe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                speMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                speMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                speMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                speMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 118, 232));
        jLabel10.setText("speciality");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_stethoscope_70px.png"))); // NOI18N

        javax.swing.GroupLayout speLayout = new javax.swing.GroupLayout(spe);
        spe.setLayout(speLayout);
        speLayout.setHorizontalGroup(
            speLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(speLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(speLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        speLayout.setVerticalGroup(
            speLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(speLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        H_ward.setPreferredSize(new java.awt.Dimension(180, 139));
        H_ward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                H_wardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                H_wardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                H_wardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                H_wardMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 118, 232));
        jLabel13.setText("Hospital Ward");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_hospital_3_70px.png"))); // NOI18N

        javax.swing.GroupLayout H_wardLayout = new javax.swing.GroupLayout(H_ward);
        H_ward.setLayout(H_wardLayout);
        H_wardLayout.setHorizontalGroup(
            H_wardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, H_wardLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(35, 35, 35))
            .addGroup(H_wardLayout.createSequentialGroup()
                .addGroup(H_wardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(H_wardLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6))
                    .addGroup(H_wardLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        H_wardLayout.setVerticalGroup(
            H_wardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, H_wardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Bed_M.setPreferredSize(new java.awt.Dimension(180, 139));
        Bed_M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bed_MMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bed_MMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bed_MMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bed_MMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 118, 232));
        jLabel9.setText("Bed Management");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_hospital_bed_70px_4.png"))); // NOI18N

        javax.swing.GroupLayout Bed_MLayout = new javax.swing.GroupLayout(Bed_M);
        Bed_M.setLayout(Bed_MLayout);
        Bed_MLayout.setHorizontalGroup(
            Bed_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bed_MLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Bed_MLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(52, 52, 52))
        );
        Bed_MLayout.setVerticalGroup(
            Bed_MLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bed_MLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(25, 25, 25))
        );

        Dep.setPreferredSize(new java.awt.Dimension(180, 139));
        Dep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DepMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DepMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(45, 118, 232));
        jLabel16.setText("Department");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_department_70px.png"))); // NOI18N

        javax.swing.GroupLayout DepLayout = new javax.swing.GroupLayout(Dep);
        Dep.setLayout(DepLayout);
        DepLayout.setHorizontalGroup(
            DepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepLayout.createSequentialGroup()
                .addGroup(DepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel15))
                    .addGroup(DepLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(DepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        DepLayout.setVerticalGroup(
            DepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Ass.setPreferredSize(new java.awt.Dimension(180, 139));
        Ass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AssMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AssMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AssMousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(45, 118, 232));
        jLabel19.setText("Assistant");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_nurse_70px_1.png"))); // NOI18N

        javax.swing.GroupLayout AssLayout = new javax.swing.GroupLayout(Ass);
        Ass.setLayout(AssLayout);
        AssLayout.setHorizontalGroup(
            AssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssLayout.createSequentialGroup()
                .addGroup(AssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AssLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel18))
                    .addGroup(AssLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        AssLayout.setVerticalGroup(
            AssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AssLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(A_med, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ass, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spe, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Dep, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(H_ward, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bed_M, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ass, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(H_ward, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Dep, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(A_med, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bed_M, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spe, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMousePressed

    private void A_medMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_medMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_A_medMouseEntered

    private void A_medMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_medMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_A_medMouseExited

    private void A_medMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_medMousePressed
        // TODO add your handling code here:

      
    }//GEN-LAST:event_A_medMousePressed

    private void speMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speMouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_speMouseEntered

    private void speMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_speMouseExited

    private void speMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speMousePressed
     
    }//GEN-LAST:event_speMousePressed

    private void H_wardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H_wardMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_H_wardMouseEntered

    private void H_wardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H_wardMouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_H_wardMouseExited

    private void H_wardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H_wardMousePressed
   
    }//GEN-LAST:event_H_wardMousePressed

    private void Bed_MMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bed_MMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Bed_MMouseEntered

    private void Bed_MMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bed_MMouseExited
        // TODO add your handling code here:
     
    }//GEN-LAST:event_Bed_MMouseExited

    private void Bed_MMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bed_MMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_Bed_MMousePressed

    private void DepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DepMouseEntered

    private void DepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DepMouseExited

    private void DepMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepMousePressed

    private void AssMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AssMouseEntered

    private void AssMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_AssMouseExited

    private void AssMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssMousePressed

    private void AssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssMouseClicked
Assistant dd=new Assistant();
        dd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_AssMouseClicked

    private void A_medMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_medMouseClicked
  Doctor dd=new Doctor();
        dd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_A_medMouseClicked

    private void DepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepMouseClicked
  Department dd=new Department();
        dd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_DepMouseClicked

    private void speMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speMouseClicked
          Speciality dd=new Speciality();
        dd.setVisible(true);
    }//GEN-LAST:event_speMouseClicked

    private void Bed_MMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bed_MMouseClicked
      BedManagement dd=new BedManagement();
        dd.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_Bed_MMouseClicked

    private void H_wardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_H_wardMouseClicked
      HospitalWard dd=new HospitalWard();
         dd.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_H_wardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A_med;
    private javax.swing.JPanel Ass;
    private javax.swing.JPanel Bed_M;
    private javax.swing.JPanel Dep;
    private javax.swing.JPanel H_ward;
    private java.awt.Label exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel spe;
    // End of variables declaration//GEN-END:variables

    private void setColor(JPanel A_med) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void resetColor(JPanel A_med) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
